version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./web/:/usr/src/web/
      - redis_socket:/redis_socket
    ports:
      - 8008:8000
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/prod/env/.data.env
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - microservice_network
      - separated_network
    extra_hosts:
      DOCKER_GATEWAY_HOST: 172.17.0.1  # Linux OS get access from docker container to localhost
      # host.docker.internal - For docker in Windows. No other action is required.
      # If You need to connect to PostgreSql in localhost, just use host.docker.internal instead of localhost
    healthcheck:
      test: curl --fail -s http://localhost:8000$$HEALTH_CHECK_URL || exit 1
      interval: 1m30s
      timeout: 3s
      retries: 3
  db:
    image: postgres:12.6-alpine
    hostname: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/.db.env
    networks:
      - separated_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 50s
      timeout: 5s
      retries: 5
  redis:
    build:
      context: .
      dockerfile: ./docker/dev/redis/Dockerfile
    restart: always
    volumes:
      - redis_data:/data
      - redis_socket:/redis_socket
    networks:
      - separated_network
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1m20s
      timeout: 5s
      retries: 3
  celery:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: celery -A src worker -l info -Q celery
    volumes:
      - redis_socket:/redis_socket
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/prod/env/.data.env
    depends_on:
      - redis
    restart: always
    networks:
      - separated_network


volumes:
  postgres_data:
  redis_data:
  redis_socket:

networks:
  microservice_network:
    driver: bridge
  separated_network:
    driver: bridge
