version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8009:8000
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/prod/env/.data.env
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - separated_network
  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/.db.env
    networks:
      - separated_network
  redis:
    image: redis:6.0.1-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - separated_network
  celery:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: celery -A src worker -l info -Q celery
    volumes:
      - ./web/:/usr/src/web/
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/prod/env/.data.env
    depends_on:
      - redis
    restart: always
    networks:
      - separated_network


volumes:
  postgres_data:
  redis_data:

networks:
  separated_network:
    driver: bridge
