version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8009:8000
    env_file:
      - docker/dev/env/.env
      - docker/prod/env/.data.env
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/db.env
  redis:
    image: redis:6.0.1-alpine
    restart: always


volumes:
  postgres_data:
