version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./web/:/home/ubuntu/web
      - static_volume:/home/ubuntu/web/static
      - media_volume:/home/ubuntu/web/media
    expose:
      - 8000
    env_file:
      - docker/prod/env/.env
      - docker/prod/env/.data.env
    depends_on:
      - db
      - redis
    restart: unless-stopped
  db:
    hostname: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/prod/env/.env.db
    restart: unless-stopped
  redis:
    image: redis:6.0.1-alpine
    restart: always
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_volume:/home/ubuntu/web/static
      - media_volume:/home/ubuntu/web/media
    ports:
      - 80:80
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:

