version: '3.7'

x-variables: &variables
  ENV_STAGE: test
  DEBUG: 0
  USE_HTTPS: 0
  ENABLE_SILK: 0
  ENABLE_SENTRY: 0
  JAEGER_AGENT_HOST: ''


services:
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
  web:
    entrypoint: /tests.sh
    restart: 'no'
    environment:
      <<: *variables
    env_file:
      - docker/prod/env/.test.env
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/prod/db/Dockerfile
    env_file:
      - docker/prod/env/.test.env
    networks:
      - separated_network

networks:
  microservice_network:
    name: dev_microservice_network
