version: '3.7'

x-variables: &variables
  ENV_STAGE: dev
  DEBUG: 1
  USE_HTTPS: 0

services:
  nginx:
    ports:
      - "9000:9000"
  web:
    environment:
      <<: *variables
      SWAGGER_URL: http://localhost:9000
  celery:
    environment:
      <<: *variables

networks:
  microservice_network:
    name: dev_microservice_network
