concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "template"
  url = "https://gitlab.com/"
  token = "your_token"
  executor = "shell"
  builds_dir =  "/home/gitlab-runner/builds"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
