version: '3.7'

services:
  runner:
    container_name: gitlab-runner
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gitlab-runner:/home/gitlab-runner
    restart: always
