version: '3.7'

services:
  celery-beat:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    entrypoint: /celery-beat.sh
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/prod/env/.data.env
    volumes:
      - redis_socket:/redis_socket
    depends_on:
      - redis
    restart: always
    networks:
      - separated_network
