# SMTP Server for mail testing

version: '3.7'

services:
  celery:
    environment:
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=0
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. http://localhost:8025/
    restart: unless-stopped
    volumes:
      - mailbox_data:/maildir


volumes:
  mailbox_data:
