name: Coverage

on:
  push:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Upload coverage to Codecov"
          uses: codecov/codecov-action@v1
          with:
            fail_ci_if_error: true
