name: Coverage

on:
  push:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run coverage.py"
        run: |
          docker-compose build
          docker-compose -f docker-compose.yml -f debug.yml run -u root web coverage run manage.py test
          docker-compose -f docker-compose.yml -f debug.yml run -u root web coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./web/

