name: Main

env:
  APP_NAME: "Template"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Run flake8
        run: |
          cd web
          flake8 .

  build:
    runs-on: ubuntu-latest
    needs: ['testing']
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_PEM }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
      - name: Check directory
        run: |
          ls -la
          pwd
          echo $USER
      - name: Deploy with rsync
        run: rsync -avz . ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/ubuntu/template/

      - name: Check docker
        run: |
          docker --version
          docker-compose --version
          docker-compose -f prod.yml -f prod.dev.yml up -d --build
