name: Flake8

env:
  APP_NAME: "Template"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Run flake8
        run: |
          cd web
          flake8 .

  build:
    runs-on: ubuntu-latest
    needs: ['testing']
    steps:
      - name: Check docker
        run: |
          docker --version
          docker-compose --version
